# -- 코드를 입력하세요
SELECT *
FROM 
(

SELECT MONTH(START_DATE) AS MONTH,A.CAR_ID/*, RECORDS_TOTAL*/,COUNT(HISTORY_ID) AS RECORDS

FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY A

JOIN (SELECT CAR_ID, COUNT(HISTORY_ID) AS RECORDS_TOTAL

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE)=2022 AND(MONTH(START_DATE)  BETWEEN 8 AND 10)

GROUP BY 1) X1 /*8~10월 총 대여량*/ ON A.CAR_ID=X1.CAR_ID

WHERE YEAR(START_DATE)=2022 AND(MONTH(START_DATE)  BETWEEN 8 AND 10)
AND RECORDS_TOTAL>4
GROUP BY 1,2
ORDER BY MONTH(START_DATE) ASC, A.CAR_ID DESC
    )F 
    WHERE RECORDS>0