# # -- 코드를 입력하세요
# SELECT h.HISTORY_ID, case 
#                 when DATEDIFF(h.END_DATE, h.START_DATE) +1>= 90 then round((c.DAILY_FEE * (1-0.15))*DATEDIFF(h.END_DATE, h.START_DATE)+1,0)
#                 when DATEDIFF(h.START_DATE, h.END_DATE)+1 >= 30 then round((c.DAILY_FEE *(1-0.08))* DATEDIFF(h.END_DATE, h.START_DATE)+1,0)
#                 when DATEDIFF(h.START_DATE, h.END_DATE) +1 >= 7 then round((c.DAILY_FEE *(1-0.05))* DATEDIFF(h.END_DATE, h.START_DATE)+1,0)
#                 else round(c.DAILY_FEE * DATEDIFF(h.END_DATE, h.START_DATE),0)
#                 end as FEE
# from CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h, CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp
# where c.CAR_ID = h.CAR_ID
# and c.CAR_TYPE = dp.CAR_TYPE
# and c.CAR_TYPE = '트럭'
# group by h.HISTORY_ID
# order by FEE desc, h.HISTORY_ID desc
WITH HISTORY AS (
    SELECT c.CAR_TYPE,
           c.DAILY_FEE,
           h.HISTORY_ID,
           DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS RENTAL_PERIOD
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT h.HISTORY_ID,
       CASE WHEN h.RENTAL_PERIOD < 7 THEN ROUND(h.RENTAL_PERIOD * h.DAILY_FEE, 0)
            WHEN h.RENTAL_PERIOD < 30 THEN ROUND(0.95 * h.RENTAL_PERIOD * h.DAILY_FEE, 0)
            WHEN h.RENTAL_PERIOD < 90 THEN ROUND(0.92 * h.RENTAL_PERIOD * h.DAILY_FEE, 0)
            ELSE ROUND(0.85 * h.RENTAL_PERIOD * h.DAILY_FEE, 0)
            END AS FEE
FROM HISTORY h
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
ON h.CAR_TYPE = d.CAR_TYPE
GROUP BY h.HISTORY_ID
ORDER BY FEE DESC, h.HISTORY_ID DESC